### ISSUE TITLE
Also set gradle version when doing a non-export build

### ISSUE THREAD

**Issue by johannesvollmer** [gilzoide/unity-gradle-wrapper#1]
Hi! We use your project successfully for exporting Android projects, thanks!

## the problem

However for the newest version, the project can be exported, but it can no longer be build & run directly (meaning, running on the device directly, without a project export). I suspect the reason is that we use a quite recent version of the gradle dependency.

`baseProjectTemplate.gradle`:
```
dependencies {
    classpath 'com.android.tools.build:gradle:7.3.0'
    **BUILD_SCRIPT_DEPS**
}
```

unity-gradle-wrapper only runs when the project is exported. But unity seems to use the `baseProjectTemplate.gradle` even when not doing exports. This seems to create some kind of version conflict, where unity uses some older gradle wrapper but the `baseProjectTemplate.gradle` specifies a recent version.

The exact error message looks roughly like this:
```
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 7.4. Current version is 6.1.1. If using the gradle wrapper, try editing the distributionUrl in ...\Temp\gradleOut\gradle\wrapper\gradle-wrapper.properties to gradle-7.4-all.zip
```

As you can see, unity does not use the version we specified in the unity-gradle-wrapper settings, which is specified to be `7.4`.

## any workarounds?
None that I can think of. I'm not 100% sure whether I assessed the problem correctly, though.

## proposed solution
It would be nice to be able to use the gradle wrapper plugin even for quick builds. It could be implemented as an additional boolean setting, something like "run only for project exports" with a default value of `true` for backwards compatibility. This would offer an opt-in solution for those who need it.

## details
unity-gradle-wrapper version: github master
unity version: Unity 2021.1.21f1
tried with gradle wrapper version `7.4` or `7.4.2` and `build:gradle:7.3.0`

**Comment by gilzoide** [comment]
Hi @johannesvollmer!

Unity's builtin Android build pipeline will use whatever version of Gradle is configured at `Preferences -> External Tools` (see "Customizing dependencies" here: https://docs.unity3d.com/Manual/android-sdksetup.html).
Even if we generate a Gradle Wrapper without exporting the project, Unity will not call Gradle using the `gradlew` script, but will rather execute something like `<path to jdk>/bin/java -jar <path to gradle>/lib/gradle-launcher-<version>.jar ...`.

So, if you want to use Gradle 7.4 with Unity's builtin pipeline, you can download it manually, configure its path in Preferences and it should work just fine. The downside of this is that it is an Editor Preference that is shared with all projects/versions of Unity.

I'm almost certain there might be a way to automate the usage of `gradlew` using editor scripts for building, with the builtin `BuildPipeline` class or the Scriptable Build Pipeline package, but if configuring Gradle globally is enough, it's a much simpler approach.

**Comment by johannesvollmer** [comment]
Thank you for those hints. We'll have a closer look, maybe switching to an older version when using `build and run`. 

Considering that unity will not use gradlew when using `build and run`, you can close the issue I guess

**Comment by gilzoide** [comment]
No problem, I hope you are able to make your builds!
If you need any more help with this, feel free to reach out again =]
